spring:
  application:
    name: DesafioTinnova
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
    initialize: true
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create