INSERT INTO veiculo (veiculo, marca, ano, descricao, vendido, created, updated) VALUES
                                                                                    ('Fiesta', 'Ford', 2015, 'Carro usado', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Civic', 'Honda', 2020, 'Carro novo', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Onix', 'Chevrolet', 2018, 'Carro seminovo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Gol', 'Volkswagen', 2010, 'Carro usado', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Corolla', 'Toyota', 2019, 'Carro novo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Ka', 'Ford', 2014, 'Carro seminovo', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('HB20', 'Hyundai', 2017, 'Carro seminovo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Cruze', 'Chevrolet', 2021, 'Carro novo', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Jetta', 'Volkswagen', 2016, 'Carro usado', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Focus', 'Ford', 2013, 'Carro seminovo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Celta', 'Chevrolet', 2009, 'Carro usado', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Fit', 'Honda', 2018, 'Carro seminovo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Yaris', 'Toyota', 2021, 'Carro novo', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('i30', 'Hyundai', 2011, 'Carro usado', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('HR-V', 'Honda', 2020, 'Carro novo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Polo', 'Volkswagen', 2020, 'Carro novo', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Mustang', 'Ford', 2022, 'Carro esportivo', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Camaro', 'Chevrolet', 2021, 'Carro esportivo', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('RAV4', 'Toyota', 2019, 'SUV', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                                                                                    ('Kicks', 'Nissan', 2021, 'SUV', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
